server:
  port: 8084

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /users/**

        - id: HOTEL-SERVICE-HOTEL
          uri: lb://HOTEL-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /hotels/**
        - id: HOTEL-SERVICE-STAFF
          uri: lb://HOTEL-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /staffs/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /ratings/**


eureka:
  instance:
    hostname: localhost